### PR TITLE
Update openvz kernel

### PR DESCRIPTION
**Pull request by Metallion**

### CODE REVIEW

**Comment by Metallion** [comment]
These CI failures were the result of my own idiocy. I filled in the environment variables wrong. :) Running the CI again with those variables filled in right.

**Comment by hansode** [comment]
If you want to update openvz, some vz related packages also should be updated.

**Comment by hansode** [comment]
Btw, our openvz driver only supports vzcore3. So we need to implement openvz driver for vzcore4.

**Comment by Metallion** [comment]
I see. The problem is that our current OpenVZ version has been removed from OpenVZ's repository.

**Comment by Metallion** [comment]
:white_check_mark: vz.1box
:white_check_mark: vz.t12-integration-rw
:white_check_mark: vz.t13-integration-rwx
:x: vz.t21-acceptance-1shot

I investigated the 1shot failure in detail and it looks like restarting the instance failed.

```
16:20:39 Running ./t.instance.lifecycle.reboot-icmp.sh
--snip--
16:20:55 test_get_instance_ipaddr
16:20:56 test_reboot_instance
16:20:56 ---
16:20:56 - i-ow05lt2o
16:20:56 test_wait_for_network_not_to_be_ready_after_rebooting
16:20:56 PING 10.0.2.100 (10.0.2.100) 56(84) bytes of data.
16:20:56 64 bytes from 10.0.2.100: icmp_seq=1 ttl=64 time=1.08 ms
16:20:56 
16:20:56 --- 10.0.2.100 ping statistics ---
16:20:56 1 packets transmitted, 1 received, 0% packet loss, time 0ms
16:20:56 rtt min/avg/max/mdev = 1.082/1.082/1.082/0.000 ms
16:20:59 [2015-09-29T16:20:59 #29618] time:1 eval:
16:21:02 PING 10.0.2.100 (10.0.2.100) 56(84) bytes of data.
16:21:02 
16:21:02 --- 10.0.2.100 ping statistics ---
16:21:02 1 packets transmitted, 0 received, 100% packet loss, time 0ms
16:21:02 
16:21:02 test_wait_for_sshd_not_to_be_ready_after_rebooting
16:21:06 [2015-09-29T16:21:06 #29618] time:1 eval:
16:21:09 [2015-09-29T16:21:09 #29618] time:2 eval:
--snip--
16:22:59 [2015-09-29T16:22:59 #29618] time:38 eval:
16:23:02 [2015-09-29T16:23:02 #29618] time:39 eval:
16:23:05 Retry Failure: Exceed 120 sec: Retried 40 times
16:23:05 ASSERT:expected:<0> but was:<1>
```

**Pull request closed without merging**
