### PR TITLE
Fix windows password complexity bug

### PR DESCRIPTION
**Pull request by triggers**

### CODE REVIEW

**Comment by Metallion** [comment]
For the sake of Murphy's law, what will happen when the 5 retries are exhausted?

**Comment by triggers** [comment]
In that case, the old password remains.  It is worth discussing whether this is an acceptable tradeoff.

**Comment by Metallion** [comment]
I think aborting the instance creation is correct behaviour. Issue https://github.com/axsh/wakame-vdc/issues/15 that I want to implement this year will inform users about what's going on

**Comment by unakatsuo** [comment]
According to https://technet.microsoft.com/en-us/library/hh994562(v=ws.10).aspx, I suspect ``GeneratePassword(10,2)`` returns the string with required complexity.

**Comment by triggers** [comment]
The problem is that ``GeneratePassword(10,2)`` can generate a password with 2 special characters and 8 lowercase letters.  The password needs another character class (numbers or uppercase letters) to have the required complexity.  So Windows rejects the password.

**Comment by Metallion** [comment]
Not sure what happened there exactly for rpmbuild.

```
20:29:53 Last 10 log lines:
20:29:53 ossl_pkey_ec.c:766: warning: assignment makes pointer from integer without a cast
20:29:53 ossl_pkey_ec.c:821: error: 'EC_GROUP_new_curve_GF2m' undeclared (first use in this function)
20:29:53 ossl_pkey_ec.c:821: error: (Each undeclared identifier is reported only once
20:29:53 ossl_pkey_ec.c:821: error: for each function it appears in.)
20:29:53 make[5]: *** [ossl_pkey_ec.o] Error 1
20:29:53 make[5]: Leaving directory `/tmp/ruby-build.20150806202800.13949/ruby-2.0.0-p247/ext/openssl'
20:29:53 make[4]: *** [ext/openssl/all] Error 2
20:29:53 make[4]: Leaving directory `/tmp/ruby-build.20150806202800.13949/ruby-2.0.0-p247'
20:29:53 make[3]: *** [build-ext] Error 2
20:29:53 make[3]: Leaving directory `/tmp/ruby-build.20150806202800.13949/ruby-2.0.0-p247'
20:29:53 make[2]: *** [ruby-stamp] Error 1
20:29:53 make[2]: Leaving directory `/root/rpmbuild/BUILD/wakame-vdc-16.0'
20:29:53 make[1]: *** [ruby-build] Error 2
20:29:53 make[1]: Leaving directory `/root/rpmbuild/BUILD/wakame-vdc-16.0'
20:29:53 error: Bad exit status from /var/tmp/rpm-tmp.1c6y1z (%build)
20:29:53 
20:29:53 
20:29:53 RPM build errors:
20:29:53     Macro %version_tag has empty body
20:29:53     Macro %version_tag has empty body
20:29:53     Bad exit status from /var/tmp/rpm-tmp.1c6y1z (%build)
20:29:53 make: *** [binary-snap] Error 1
20:29:53 [ERROR] xexecscript failed: exitcode=1 (distro.sh:1865)
```

Let's try that again.

**Pull request merged**
