### PR TITLE
Terraform vendoring

### PR DESCRIPTION
**Pull request by unakatsuo**
It makes building terraform plugin easy. No need for `go get` prior to `go build`. 
Imported dependencies for terraform v0.6.16.

### CODE REVIEW

**Comment by Metallion** [comment]
Isn't it a little excessive to keep source code for the entire dependency tree in our github repository? What exactly is the problem with running `go get`?

**Comment by unakatsuo** [comment]
[Understanding and using the vendor folder](https://blog.gopheracademy.com/advent-2015/vendor-folder/) explains details of go vendoring culture.

`go get` just checks out `master` branch for each dependency. That means that the `go build` results in whether fail or success upon when you ran `go get`.

I also felt same thing for their strategy to avoid the problem but it is admitted as a Go lang standard since Go 1.5.

**Comment by unakatsuo** [comment]
Another way is to just maintain `vendor/vendor.json` which is similar to `Gemfile.lock` on Ruby. A drawback is that the build process requires to have `govendor` binary and run it prior to `go build`.

The build process would be changed to:

``` shell
go get -u github.com/kardianos/govendor
$GOPATH/bin/govendor sync
go build
```

I am going to remove the change `9bcda67` which has 400 files and just commit `vendor/vendor.json` instead if you agree to this way is more reasonable.

**Comment by YamazakiYasuhiro** [comment]
@Metallion Please consider this patch for merging at first. The LXC provider in Terraform is not suitable for our use case. We will need to extend more this feature, the Wakame-vdc Provider, asap. Thanks.

**Comment by Metallion** [comment]
The code looks good to me but I'm a little worried about the lack of testing. I understand the go CI jobs aren't set up properly yet but could you confirm that the go test command works? If the tests are working after vendoring like described in this readme, I think it's good to merge.

Go ahead and merge while I'm away **if** you can confirm that the tests are working as described in the readme here: https://github.com/axsh/wakame-vdc/blob/39f44248c0e2595cad64a7ae66abe5b5c09cd24a/client/terraform-provider-wakamevdc/README.md#testing-the-provider

We really should finish setting up the CI to run them automatically though. Work has started on it including [this job](http://ci.wakame.jp/job/vz.1box-plus-go-tests/) but I'm not sure how much of it was finished.

**Comment by unakatsuo** [comment]
```
[centos@wakame-vdc-1box ~]$ go version
go version go1.7.1 linux/amd64
[centos@wakame-vdc-1box ~]$ echo $GOPATH
/home/centos/go
[centos@wakame-vdc-1box ~]$ cd $GOPATH/src/github.com/axsh
[centos@wakame-vdc-1box axsh]$ pwd
/home/centos/go/src/github.com/axsh
[centos@wakame-vdc-1box axsh]$ git clone --depth=1 --branch=terraform-vendoring https://github.com/axsh/wakame-vdc.git
Initialized empty Git repository in /home/centos/go/src/github.com/axsh/wakame-vdc/.git/
remote: Counting objects: 7952, done.
remote: Compressing objects:  13% (704/5414)   
remote: Compressing objects:  27% (1462/5414)   
remote: Compressing objects:  41% (2220/5414)   
remote: Compressing objects:  55% (2978/5414)   
remote: Compressing objects:  69% (3736/5414)   
remote: Compressing objects:  83% (4494/5414)   
remote: Compressing objects:  97% (5252/5414)   
remote: Compressing objects: 100% (5414/5414), done.
Receiving objects:  11% (875/7952), 132.00 KiB | 114 KiB/s   
Receiving objects:  22% (1750/7952), 252.00 KiB | 152 KiB/s   
Receiving objects:  33% (2625/7952), 372.00 KiB | 173 KiB/s   
Receiving objects:  43% (3420/7952), 708.00 KiB | 224 KiB/s   
Receiving objects:  54% (4295/7952), 1012.00 KiB | 236 KiB/s   
Receiving objects:  58% (4621/7952), 3.39 MiB | 406 KiB/s      
Receiving objects:  67% (5328/7952), 5.03 MiB | 467 KiB/s   
Receiving objects:  77% (6124/7952), 5.73 MiB | 465 KiB/s   
Receiving objects:  85% (6780/7952), 7.83 MiB | 466 KiB/s   
Receiving objects:  95% (7555/7952), 8.54 MiB | 465 KiB/s   
remote: Total 7952 (delta 3901), reused 5237 (delta 2142), pack-reused 0
Receiving objects: 100% (7952/7952), 9.10 MiB | 466 KiB/s, done.
Resolving deltas:  19% (703/3901)   
Resolving deltas:  38% (1486/3901)   
Resolving deltas:  57% (2229/3901)   
Resolving deltas:  76% (2978/3901)   
Resolving deltas:  95% (3709/3901)   
Resolving deltas: 100% (3901/3901), done.
[centos@wakame-vdc-1box axsh]$ go get -u github.com/kardianos/govendor
[centos@wakame-vdc-1box axsh]$ cd wakame-vdc/client/go-wakamevdc/
[centos@wakame-vdc-1box go-wakamevdc]$ time govendor sync

real    0m2.571s
user    0m0.046s
sys 0m0.095s
[centos@wakame-vdc-1box go-wakamevdc]$ cd ../
[centos@wakame-vdc-1box client]$ ls
dolphin  go-wakamevdc  mussel  ruby-hijiki  terraform-provider-wakamevdc
[centos@wakame-vdc-1box client]$ cd terraform-provider-wakamevdc/
[centos@wakame-vdc-1box terraform-provider-wakamevdc]$ time govendor sync

real    5m7.228s
user    0m6.343s
sys 0m6.293s
[centos@wakame-vdc-1box terraform-provider-wakamevdc]$ go build
[centos@wakame-vdc-1box terraform-provider-wakamevdc]$ export WAKAMEVDC_API_ENDPOINT="http://192.:9001/api/12.03/"
localhost:9001/api/12.03/"
[centos@wakame-vdc-1box terraform-provider-wakamevdc]$ go test -v
?       github.com/axsh/wakame-vdc/client/terraform-provider-wakamevdc  [no test files]
[centos@wakame-vdc-1box terraform-provider-wakamevdc]$ cd wakamevdc/
[centos@wakame-vdc-1box wakamevdc]$ go test -v
=== RUN   TestResourceWakamevdcInstance
--- SKIP: TestResourceWakamevdcInstance (0.00s)
    testing.go:198: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestResourceWakamevdcNetworkFull
--- SKIP: TestResourceWakamevdcNetworkFull (0.00s)
    testing.go:198: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestResourceWakamevdcSecurityGroupMinimal
--- SKIP: TestResourceWakamevdcSecurityGroupMinimal (0.00s)
    testing.go:198: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestResourceWakamevdcSecurityGroupFull
--- SKIP: TestResourceWakamevdcSecurityGroupFull (0.00s)
    testing.go:198: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestResourceWakamevdcSSHKeyCreateUpdateDelete
--- SKIP: TestResourceWakamevdcSSHKeyCreateUpdateDelete (0.00s)
    testing.go:198: Acceptance tests skipped unless env 'TF_ACC' set
PASS
ok      github.com/axsh/wakame-vdc/client/terraform-provider-wakamevdc/wakamevdc    0.003s
[centos@wakame-vdc-1box wakamevdc]$ exit
```

**Pull request merged**
