### PR TITLE
add image "update" task.

### PR DESCRIPTION
**Pull request by hansode**
### Feature

This change will provide image `update` task

```
$ mussel image update wmi-xxx --display-name display-name
```

### CODE REVIEW

**Comment by Metallion** [comment]
Why did kvm.smoke fail once?

**Comment by hansode** [comment]
CI was very busy and had some jobs. Therefore a new worker was failed to run.

via error message:
> `Failed to allocate 4294967296 B: Cannot allocate memory`

**Comment by Metallion** [comment]
Looks like the CI needs some maintenance then. It should not be allowed to run more jobs than it can handle.

**Comment by Metallion** [comment]
We still need to discuss the CI issue but this can be merged in the meantime.

**Pull request merged**
