### PR TITLE
Update wakame-vdc URL in the rpm spec files

### PR DESCRIPTION
**Pull request by Metallion**

### CODE REVIEW

**Comment by Metallion** [comment]
The usual IP address scheduler race condition again. Can't wait to get that fixed.

```
18:46:19 Failures:
18:46:19 
18:46:19   1) Dcmgr::Scheduler::IPAddress::Incremental#schedule happy paths when previously assigned addresses have been released reassigns the lowest available address
18:46:19      Failure/Error: expect(subject).to eq "192.168.0.3"
18:46:19        
18:46:19        expected: "192.168.0.3"
18:46:19             got: "192.168.0.6"
18:46:19        
18:46:19        (compared using ==)
18:46:19      Shared Example Group: "reassign released addresses" called from ./spec/dcmgr/scheduler/ip_address/incremental_spec.rb:32
18:46:19      # ./spec/dcmgr/scheduler/ip_address/incremental_examples/reassign_released_addresses.rb:18:in `block (3 levels) in <top (required)>'
18:46:19 
18:46:19 Finished in 15.92 seconds (files took 0.57245 seconds to load)
18:46:19 77 examples, 1 failure
```

**Comment by hansode** [comment]
> 4aa0eae failure - wakame-ci/rpmbuild

```
19:26:39 + curl -fsSkL http://dlc.wakame.axsh.jp.s3.amazonaws.com/packages/rhel/6/current/x86_64/kmod-openvswitch-1.6.1-1.el6.x86_64.rpm -o tests/vdc.sh.d/rhel/vendor/x86_64/kmod-openvswitch-1.6.1-1.el6.x86_64.rpm
19:27:43 curl: (7) couldn't connect to host
```

having a s3 trouble today.

**Comment by hansode** [comment]
> 4aa0eae failure - wakame-ci/kvm.smoke

```
21:05:29 [kvm.1box] $ /bin/bash /tmp/build_step_template2069643984676729609.sh
21:05:30 time sudo VDC_HYPERVISOR=kvm VDC_EDGE_NETWORKING=netfilter setarch x86_64 ./vmbuilder/kvm/rhel/6/misc/kvm-ctl.sh build --config-path=./vmbuilder.conf
21:05:30 [INFO] Creating disk image: "/var/lib/jenkins/workspace/kvm.1box/1box-kvm.netfilter.x86_64.raw" of size: 20480MB
21:05:30 [INFO] Adding partition table to disk image: /var/lib/jenkins/workspace/kvm.1box/1box-kvm.netfilter.x86_64.raw
21:05:31 [INFO] Partition at beginning of disk - reserving first cylinder
21:05:31 [INFO] Adding type ext2 partition to disk image: /var/lib/jenkins/workspace/kvm.1box/1box-kvm.netfilter.x86_64.raw
21:05:31 Warning: The resulting partition is not properly aligned for best performance.
```

lxc + device-mapper issue.

**Comment by hansode** [comment]
> 4aa0eae failure - wakame-ci/kvm.smoke.lb

```
21:05:38 [kvm.1box] $ /bin/bash /tmp/build_step_template3645904023882311009.sh
21:05:38 time sudo VDC_HYPERVISOR=kvm VDC_EDGE_NETWORKING=netfilter setarch x86_64 ./vmbuilder/kvm/rhel/6/misc/kvm-ctl.sh build --config-path=./vmbuilder.conf
21:05:38 [INFO] Creating disk image: "/var/lib/jenkins/workspace/kvm.1box/1box-kvm.netfilter.x86_64.raw" of size: 20480MB
21:05:38 [INFO] Adding partition table to disk image: /var/lib/jenkins/workspace/kvm.1box/1box-kvm.netfilter.x86_64.raw
21:05:38 [INFO] Partition at beginning of disk - reserving first cylinder
21:05:38 [INFO] Adding type ext2 partition to disk image: /var/lib/jenkins/workspace/kvm.1box/1box-kvm.netfilter.x86_64.raw
21:05:38 Warning: The resulting partition is not properly aligned for best performance.
```

lxc + device-mapper issue.

**Comment by hansode** [comment]
:+1:

**Pull request merged**
