### PR TITLE
Feature mussel rpm

### PR DESCRIPTION
**Pull request by hansode**
The detail is #545.

### CODE REVIEW

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ sudo yum install  wakame-vdc
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
epel/metalink                                                                                                               | 4.2 kB     00:00
 * base: mirror.fairway.ne.jp
 * elrepo: repos.lax-noc.com
 * epel: mirror01.idc.hinet.net
 * extras: mirror.vodien.com
 * updates: mirror.vodien.com
epel                                                                                                                        | 4.4 kB     00:00
epel/primary_db                                                                                                             | 6.5 MB     00:00
http://www.graphviz.org/pub/graphviz/stable/redhat/el6.6/x86_64/os/repodata/repomd.xml: [Errno 12] Timeout on http://www.graphviz.org/pub/graphviz/stable/redhat/el6.6/x86_64/os/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
Resolving Dependencies
--> Running transaction check
---> Package wakame-vdc.x86_64 0:15.03-20150424154559git8eb3f1b.el6 will be installed
--> Processing Dependency: wakame-vdc-ruby < 2.0.1 for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Processing Dependency: wakame-vdc-ruby >= 2.0.0.247 for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Processing Dependency: prelink for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Processing Dependency: parted for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Processing Dependency: mysql for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Processing Dependency: libxslt for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Processing Dependency: jemalloc for package: wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
--> Running transaction check
---> Package jemalloc.x86_64 0:3.6.0-1.el6 will be installed
---> Package libxslt.x86_64 0:1.1.26-2.el6_3.1 will be installed
---> Package mysql.x86_64 0:5.1.73-3.el6_5 will be installed
---> Package parted.x86_64 0:2.1-25.el6 will be installed
---> Package prelink.x86_64 0:0.4.6-3.1.el6_4 will be installed
---> Package wakame-vdc-ruby.x86_64 0:2.0.0.598.axsh0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                         Arch                   Version                                             Repository                        Size
===================================================================================================================================================
Installing:
 wakame-vdc                      x86_64                 15.03-20150424154559git8eb3f1b.el6                  wakame-vdc-rhel6                  62 M
Installing for dependencies:
 jemalloc                        x86_64                 3.6.0-1.el6                                         epel                             100 k
 libxslt                         x86_64                 1.1.26-2.el6_3.1                                    base                             452 k
 mysql                           x86_64                 5.1.73-3.el6_5                                      base                             894 k
 parted                          x86_64                 2.1-25.el6                                          base                             607 k
 prelink                         x86_64                 0.4.6-3.1.el6_4                                     base                             993 k
 wakame-vdc-ruby                 x86_64                 2.0.0.598.axsh0-1                                   wakame-3rd-rhel6                  21 M

Transaction Summary
===================================================================================================================================================
Install       7 Package(s)

Total download size: 86 M
Installed size: 281 M
Is this ok [y/N]: y
Downloading Packages:
(1/7): jemalloc-3.6.0-1.el6.x86_64.rpm                                                                                      | 100 kB     00:00
(2/7): libxslt-1.1.26-2.el6_3.1.x86_64.rpm                                                                                  | 452 kB     00:01
(3/7): mysql-5.1.73-3.el6_5.x86_64.rpm                                                                                      | 894 kB     00:03
(4/7): parted-2.1-25.el6.x86_64.rpm                                                                                         | 607 kB     00:03
(5/7): prelink-0.4.6-3.1.el6_4.x86_64.rpm                                                                                   | 993 kB     00:03
(6/7): wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64.rpm                                                             |  62 MB     00:05
(7/7): wakame-vdc-ruby-2.0.0.598.axsh0-1.x86_64.rpm                                                                         |  21 MB     00:01
---------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                              4.0 MB/s |  86 MB     00:21
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
Importing GPG key 0x0608B895:
 Userid : EPEL (6) <epel@fedoraproject.org>
 Package: epel-release-6-8.noarch (installed)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Installing : libxslt-1.1.26-2.el6_3.1.x86_64                                                                                                 1/7
  Installing : wakame-vdc-ruby-2.0.0.598.axsh0-1.x86_64                                                                                        2/7
  Installing : prelink-0.4.6-3.1.el6_4.x86_64                                                                                                  3/7
  Installing : jemalloc-3.6.0-1.el6.x86_64                                                                                                     4/7
  Installing : mysql-5.1.73-3.el6_5.x86_64                                                                                                     5/7
  Installing : parted-2.1-25.el6.x86_64                                                                                                        6/7
  Installing : wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64                                                                            7/7
  Verifying  : parted-2.1-25.el6.x86_64                                                                                                        1/7
  Verifying  : wakame-vdc-ruby-2.0.0.598.axsh0-1.x86_64                                                                                        2/7
  Verifying  : wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64                                                                            3/7
  Verifying  : mysql-5.1.73-3.el6_5.x86_64                                                                                                     4/7
  Verifying  : jemalloc-3.6.0-1.el6.x86_64                                                                                                     5/7
  Verifying  : prelink-0.4.6-3.1.el6_4.x86_64                                                                                                  6/7
  Verifying  : libxslt-1.1.26-2.el6_3.1.x86_64                                                                                                 7/7

Installed:
  wakame-vdc.x86_64 0:15.03-20150424154559git8eb3f1b.el6

Dependency Installed:
  jemalloc.x86_64 0:3.6.0-1.el6       libxslt.x86_64 0:1.1.26-2.el6_3.1             mysql.x86_64 0:5.1.73-3.el6_5    parted.x86_64 0:2.1-25.el6
  prelink.x86_64 0:0.4.6-3.1.el6_4    wakame-vdc-ruby.x86_64 0:2.0.0.598.axsh0-1

Complete!
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ ls -la /opt/axsh/wakame-vdc/client/
total 20
drwxr-xr-x  5 root root 4096 Apr 24 16:18 .
drwxr-xr-x 11 root root 4096 Apr 24 16:18 ..
drwxr-xr-x  3 root root 4096 Apr 24 16:18 dolphin
drwxr-xr-x  6 root root 4096 Apr 24 16:18 mussel
drwxr-xr-x  4 root root 4096 Apr 24 16:18 ruby-hijiki
[vagrant@vagrant-centos6 yum.repos.d]$ ls -la /opt/axsh/wakame-vdc/client/mussel/
total 52
drwxr-xr-x 6 root root 4096 Apr 24 16:18 .
drwxr-xr-x 5 root root 4096 Apr 24 16:18 ..
drwxr-xr-x 2 root root 4096 Apr 24 16:18 dolphin.d
-rw-r--r-- 1 root root 7864 Apr 24 15:51 functions
-rw-r--r-- 1 root root 2176 Apr 24 15:51 functions_dolphin
-rw-r--r-- 1 root root   43 Apr 24 15:51 Makefile
drwxr-xr-x 2 root root 4096 Apr 24 16:18 misc
-rwxr-xr-x 1 root root  458 Apr 24 15:51 mussel_dolphin.sh
-rwxr-xr-x 1 root root  701 Apr 24 15:51 mussel.sh
-rw-r--r-- 1 root root  740 Apr 24 15:51 README.md
drwxr-xr-x 9 root root 4096 Apr 24 16:18 test
drwxr-xr-x 2 root root 4096 Apr 24 16:18 v12.03.d
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ sudo yum install wakame-vdc-client-mussel
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.fairway.ne.jp
 * elrepo: mirror.uta.edu.ec
 * epel: mirror01.idc.hinet.net
 * extras: mirror.vodien.com
 * updates: mirror.vodien.com
http://www.graphviz.org/pub/graphviz/stable/redhat/el6.6/x86_64/os/repodata/repomd.xml: [Errno 12] Timeout on http://www.graphviz.org/pub/graphviz/stable/redhat/el6.6/x86_64/os/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
Resolving Dependencies
--> Running transaction check
---> Package wakame-vdc-client-mussel.noarch 0:15.03-20150424154559git8eb3f1b.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                                Arch                 Version                                          Repository                      Size
===================================================================================================================================================
Installing:
 wakame-vdc-client-mussel               noarch               15.03-20150424154559git8eb3f1b.el6               wakame-vdc-rhel6                91 k

Transaction Summary
===================================================================================================================================================
Install       1 Package(s)

Total download size: 91 k
Installed size: 376 k
Is this ok [y/N]: y
Downloading Packages:
wakame-vdc-client-mussel-15.03-20150424154559git8eb3f1b.el6.noarch.rpm                                                      |  91 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : wakame-vdc-client-mussel-15.03-20150424154559git8eb3f1b.el6.noarch                                                              1/1
  Verifying  : wakame-vdc-client-mussel-15.03-20150424154559git8eb3f1b.el6.noarch                                                              1/1

Installed:
  wakame-vdc-client-mussel.noarch 0:15.03-20150424154559git8eb3f1b.el6

Complete!
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ sudo rpm -qf /opt/axsh/wakame-vdc/client/mussel/
wakame-vdc-15.03-20150424154559git8eb3f1b.el6.x86_64
wakame-vdc-client-mussel-15.03-20150424154559git8eb3f1b.el6.noarch
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ ls -la /opt/axsh/wakame-vdc/client/
total 8
drwxr-xr-x 2 root root 4096 Apr 24 16:52 .
drwxr-xr-x 4 root root 4096 Apr 24 16:52 ..
[vagrant@vagrant-centos6 yum.repos.d]$ sudo yum crean metadata
Loaded plugins: fastestmirror
No such command: crean. Please use /usr/bin/yum --help
[vagrant@vagrant-centos6 yum.repos.d]$ sudo yum clean  metadata
Loaded plugins: fastestmirror
Cleaning repos: base elrepo epel extras updates wakame-3rd-rhel6 wakame-vdc-rhel6
19 metadata files removed
7 sqlite files removed
0 metadata files removed
[vagrant@vagrant-centos6 yum.repos.d]$ sudo yum install wakame-vdc
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
epel/metalink                                                                                                               | 4.2 kB     00:00
 * base: mirror.vodien.com
 * elrepo: repos.mia.lax-noc.com
 * epel: ftp.kddilabs.jp
 * extras: mirror.fairway.ne.jp
 * updates: mirror.vodien.com
base                                                                                                                        | 3.7 kB     00:00
base/primary_db                                                                                                             | 4.6 MB     00:01
elrepo                                                                                                                      | 2.9 kB     00:00
elrepo/primary_db                                                                                                           | 717 kB     00:01
epel                                                                                                                        | 4.4 kB     00:00
epel/primary_db                                                                                                             | 6.5 MB     00:00
extras                                                                                                                      | 3.4 kB     00:00
extras/primary_db                                                                                                           |  30 kB     00:00
updates                                                                                                                     | 3.4 kB     00:00
updates/primary_db                                                                                                          | 3.2 MB     00:01
wakame-3rd-rhel6                                                                                                            | 2.9 kB     00:00
wakame-3rd-rhel6/primary_db                                                                                                 | 3.1 kB     00:00
wakame-vdc-rhel6                                                                                                            | 2.9 kB     00:00
wakame-vdc-rhel6/primary_db                                                                                                 |  28 kB     00:00
Resolving Dependencies
--> Running transaction check
---> Package wakame-vdc.x86_64 0:15.03-20150424163304gitd93dd1d.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                     Arch                    Version                                               Repository                         Size
===================================================================================================================================================
Installing:
 wakame-vdc                  x86_64                  15.03-20150424163304gitd93dd1d.el6                    wakame-vdc-rhel6                   62 M

Transaction Summary
===================================================================================================================================================
Install       1 Package(s)

Total download size: 62 M
Installed size: 203 M
Is this ok [y/N]: y
Downloading Packages:
wakame-vdc-15.03-20150424163304gitd93dd1d.el6.x86_64.rpm                                                                    |  62 MB     00:10
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : wakame-vdc-15.03-20150424163304gitd93dd1d.el6.x86_64                                                                            1/1
  Verifying  : wakame-vdc-15.03-20150424163304gitd93dd1d.el6.x86_64                                                                            1/1

Installed:
  wakame-vdc.x86_64 0:15.03-20150424163304gitd93dd1d.el6

Complete!
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ ls -la /opt/axsh/wakame-vdc/client/
total 16
drwxr-xr-x  4 root root 4096 Apr 24 16:53 .
drwxr-xr-x 11 root root 4096 Apr 24 16:54 ..
drwxr-xr-x  3 root root 4096 Apr 24 16:53 dolphin
drwxr-xr-x  4 root root 4096 Apr 24 16:53 ruby-hijiki
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ sudo yum install wakame-vdc-client-mussel
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.vodien.com
 * elrepo: ftp.ne.jp
 * epel: ftp.kddilabs.jp
 * extras: mirror.fairway.ne.jp
 * updates: mirror.vodien.com
Resolving Dependencies
--> Running transaction check
---> Package wakame-vdc-client-mussel.noarch 0:15.03-20150424163304gitd93dd1d.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                                Arch                 Version                                          Repository                      Size
===================================================================================================================================================
Installing:
 wakame-vdc-client-mussel               noarch               15.03-20150424163304gitd93dd1d.el6               wakame-vdc-rhel6                91 k

Transaction Summary
===================================================================================================================================================
Install       1 Package(s)

Total download size: 91 k
Installed size: 376 k
Is this ok [y/N]: y
Downloading Packages:
wakame-vdc-client-mussel-15.03-20150424163304gitd93dd1d.el6.noarch.rpm                                                      |  91 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : wakame-vdc-client-mussel-15.03-20150424163304gitd93dd1d.el6.noarch                                                              1/1
  Verifying  : wakame-vdc-client-mussel-15.03-20150424163304gitd93dd1d.el6.noarch                                                              1/1

Installed:
  wakame-vdc-client-mussel.noarch 0:15.03-20150424163304gitd93dd1d.el6

Complete!
```

**Comment by t-iwano** [comment]
```
[vagrant@vagrant-centos6 yum.repos.d]$ ls -la /opt/axsh/wakame-vdc/client/
total 20
drwxr-xr-x  5 root root 4096 Apr 24 16:55 .
drwxr-xr-x 11 root root 4096 Apr 24 16:54 ..
drwxr-xr-x  3 root root 4096 Apr 24 16:53 dolphin
drwxr-xr-x  6 root root 4096 Apr 24 16:55 mussel
drwxr-xr-x  4 root root 4096 Apr 24 16:53 ruby-hijiki
[vagrant@vagrant-centos6 yum.repos.d]$ ls -la /opt/axsh/wakame-vdc/client/mussel/
total 52
drwxr-xr-x 6 root root 4096 Apr 24 16:55 .
drwxr-xr-x 5 root root 4096 Apr 24 16:55 ..
drwxr-xr-x 2 root root 4096 Apr 24 16:55 dolphin.d
-rw-r--r-- 1 root root 7864 Apr 24 16:39 functions
-rw-r--r-- 1 root root 2176 Apr 24 16:39 functions_dolphin
-rw-r--r-- 1 root root   43 Apr 24 16:39 Makefile
drwxr-xr-x 2 root root 4096 Apr 24 16:55 misc
-rwxr-xr-x 1 root root  458 Apr 24 16:39 mussel_dolphin.sh
-rwxr-xr-x 1 root root  701 Apr 24 16:39 mussel.sh
-rw-r--r-- 1 root root  740 Apr 24 16:39 README.md
drwxr-xr-x 9 root root 4096 Apr 24 16:55 test
drwxr-xr-x 2 root root 4096 Apr 24 16:55 v12.03.d
```

**Comment by Metallion** [comment]
After installing the RPM, it should be possible to run the `mussel` command from any directory without having to modify the `PATH` variable.

Can you add a wrapper script `/usr/bin/mussel` that calls `/opt/axsh/wakame-vdc/client/mussel/mussel.sh`?

**Comment by Metallion** [comment]
Also, this might be a different issue but it would be a good idea to add a usage output when calling mussel without arguments. Currently it shows an error that will be very hard to understand for new users.

```
[18:35:30] centos@joske  (~) > /opt/axsh/wakame-vdc/client/mussel/mussel.sh
Error: an inet prefix is expected rather than "localhost".
[ERROR] 'namespace' is empty (functions:248)

[18:36:37] centos@joske  (~) > /opt/axsh/wakame-vdc/client/mussel/mussel.sh help
Error: an inet prefix is expected rather than "localhost".
[ERROR] 'cmd' is empty (functions:249)
```

**Comment by Metallion** [comment]
The RPM packages were removed in the weekly CI environment rebuild. Rerunning to CI to rebuild them.

**Comment by Metallion** [comment]
Looks good to me. I will merge when @t-iwano gives his +1.

**Comment by t-iwano** [comment]
:+1:

**Comment by Metallion** [comment]
The dummy.smoke failure appears to be an issue where yum repository data couldn't be downloaded. Looking at Jenkins' log, it doesn't occur often enough to be a serious issue yet.

**Pull request merged**
