### PR TITLE
Updated download path for virtio-win-0.1-74.iso

### PR DESCRIPTION
**Pull request by triggers**

### CODE REVIEW

**Comment by Metallion** [comment]
I see this is a deprecated iso. What is the reason to keep using it?

**Comment by triggers** [comment]
The reason to keep using it is because we have a lot of experience with it and have not noticed any problems, either during install or when running the VM.  I would prefer to wait until we have more of the Windows testing automated before we update.

**Comment by Metallion** [comment]
Alright. That sounds reasonable.

Is the Windows image building currently included in the CI?

**Comment by triggers** [comment]
Kind of.  It is in there but is not run automatically (and has not been run from CI in a long time).  It is probably not worth running automatically until do automatic tests with the resulting images.

**Comment by Metallion** [comment]
Since the CI is rebuilt daily, I think it would be a good idea to rebuilt the Windows images daily as well. That way we will notice when the scripts break.

Anyway, this PR looks good. :+1:

**Pull request merged**
