### PR TITLE
dcmgr: remove unused ops scripts.

### PR DESCRIPTION
**Pull request by hansode**
Related to #650

### Problem

Under dcmgr/ops files are not used.
I commited these files for debugging. But recently I never used them.

### Solution

Just cleanup files.

### CODE REVIEW

**Comment by hansode** [comment]
> 052b95e failure - wakame-ci/dummy.smoke

the failed reason was same as #584:

```
14:38:50 2015-07-17 14:34:26 JobContext thr=JobWorker[0/1] [INFO]: Job complete 9c5ddd0e6552a7a9cbccc532270f59b552c9783a (Local ID: 9c5ddd0e6552a7a9cbccc532270f59b552c9783a)[ schedule_instance ]: 0.035605687 sec
14:38:50 I, [2015-07-17T14:34:26.978571 #1980]  INFO -- AlarmCollector: event_caught: ["i-q5707izh"]
14:38:50 I, [2015-07-17T14:34:30.668361 #1980]  INFO -- HvaCollector: finalize_instance(i-q5707izh) terminated at=2015-07-17 05:34:30 UTC
14:38:50 I, [2015-07-17T14:34:30.686421 #1980]  INFO -- AlarmCollector: event_caught: ["i-q5707izh"]
14:38:50 I, [2015-07-17T14:34:30.686994 #1980]  INFO -- EventHook: event caught: ["i-q5707izh"]
14:38:50 I, [2015-07-17T14:34:30.687811 #1980]  INFO -- AlarmCollector: event_caught: ["i-q5707izh"]
14:38:50 2015-07-17 14:34:35 Node thr=#<Thread:0x007f9f2d593d40> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=collector.master, token=da8b9
```

**Comment by hansode** [comment]
> 052b95e failure - wakame-ci/kvm.smoke

same as #584:

```
15:09:11 2015-07-17 15:02:52 JobContext thr=JobWorker[0/1] [INFO]: Job start 3ca6186e2a76fa16f26d1899475a425e47b86f35 (Local ID: 3ca6186e2a76fa16f26d1899475a425e47b86f35)[ schedule_instance ]
15:09:11 I, [2015-07-17T15:02:52.074159 #13153]  INFO -- LeastUsage: Session ID: 3ca6186e2a76fa16f26d1899475a425e47b86f35: Scheduling host node hva.1box64 for the instance i-tqjfbota
15:09:11 I, [2015-07-17T15:02:52.075654 #13153]  INFO -- PerInstance: Session ID: 3ca6186e2a76fa16f26d1899475a425e47b86f35: Selected network scheduler:  Dcmgr::Scheduler::Network::VifsRequestParam for the instance i-tqjfbota
15:09:11 2015-07-17 15:02:56 Node thr=#<Thread:0x007fc637593d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=collector.master, token=d40e7
```

**Comment by hansode** [comment]
> 052b95e failure - wakame-ci/dummy.smoke

same as #584:

```
18:09:34 2015-07-17 18:05:11 JobContext thr=JobWorker[0/1] [INFO]: Job complete 6ca9515e72ad83c4b5a10fb22ce6f64099c8b23b (Local ID: 6ca9515e72ad83c4b5a10fb22ce6f64099c8b23b)[ schedule_instance ]: 0.055799842 sec
18:09:34 I, [2015-07-17T18:05:11.571625 #1946]  INFO -- AlarmCollector: event_caught: ["i-9b8ounwd"]
18:09:34 I, [2015-07-17T18:05:15.336013 #1946]  INFO -- HvaCollector: finalize_instance(i-9b8ounwd) terminated at=2015-07-17 09:05:15 UTC
18:09:34 I, [2015-07-17T18:05:15.353283 #1946]  INFO -- EventHook: event caught: ["i-9b8ounwd"]
18:09:34 I, [2015-07-17T18:05:15.353832 #1946]  INFO -- AlarmCollector: event_caught: ["i-9b8ounwd"]
18:09:34 I, [2015-07-17T18:05:15.355870 #1946]  INFO -- AlarmCollector: event_caught: ["i-9b8ounwd"]
18:09:34 2015-07-17 18:05:20 Node thr=#<Thread:0x007f4c97593d38> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=collector.master, token=ee6ff
```

**Comment by hansode** [comment]
> 052b95e failure - wakame-ci/vz.smoke

1box build failed.
* download failed

**Comment by hansode** [comment]
> 052b95e failure - wakame-ci/vz.smoke

1box build failed.
* download failed

it looks specific worker issue. :(

**Comment by hansode** [comment]
> 052b95e failure - wakame-ci/vz.smoke

got some mysql erros.
this is first time to see.

```
13:19:13 2015-07-18 13:12:33 JobContext thr=JobWorker[0/1] [INFO]: Job complete 5a375d4ce11702221928bbc329e1e77de4ddf56d (Local ID: 5a375d4ce11702221928bbc329e1e77de4ddf56d)[ schedule_instance ]: 0.081290578 sec
13:19:13 I, [2015-07-18T13:12:49.317645 #2060]  INFO -- AlarmCollector: event_caught: ["i-rsr8pd92"]
13:19:13 2015-07-18 13:12:53 ThreadPool thr=DataStore[0/1] [ERROR]: Caught Sequel::DatabaseDisconnectError: Mysql2::Error: This connection is still waiting for a result, try again once you have the result
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/logging.rb:58:in `query'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/logging.rb:58:in `block in log_connection_execute'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/logging.rb:33:in `log_yield'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/logging.rb:58:in `log_connection_execute'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:271:in `commit_transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/adapters/shared/mysql.rb:319:in `commit_transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:256:in `commit_or_rollback_transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:138:in `ensure in _transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:150:in `_transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:102:in `block in transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/connecting.rb:236:in `synchronize'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:95:in `transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/data_store.rb:52:in `process_single_tx'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/data_store.rb:38:in `block in pass'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `block (2 levels) in initialize'
```

```
13:19:13 10.0.2.2 - - [18/Jul/2015:13:09:25 +0900] "POST /api/12.03/ssh_key_pairs.yml HTTP/1.1" 200 760 0.0701
13:19:13 Dcmgr::Models::InvalidUUIDError - Invalid uuid or unsupported uuid:  in Dcmgr::Models::Network:
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/models/base_new.rb:230:in `trim_uuid'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/models/base_new.rb:213:in `[]'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb:37:in `check_dc_network'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb:288:in `block (3 levels) in load_namespace'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb:263:in `each'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb:263:in `block (2 levels) in load_namespace'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `block in compile!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `[]'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/sinatra/sequel_transaction.rb:57:in `block in route_eval'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:127:in `_transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:102:in `block in transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/connecting.rb:236:in `synchronize'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sequel-3.47.0/lib/sequel/database/transactions.rb:95:in `transaction'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/sinatra/sequel_transaction.rb:55:in `route_eval'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/rack/request_logger.rb:28:in `_call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/rack/request_logger.rb:20:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:212:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:580:in `process_client'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:52:in `process_client'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-worker-killer-0.4.3/lib/unicorn/worker_killer.rb:92:in `process_client'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/oob_gc.rb:60:in `process_client'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:660:in `worker_loop'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:527:in `spawn_missing_workers'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:153:in `start'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/unicorn-4.7.0/bin/unicorn:126:in `<top (required)>'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/bin/unicorn:23:in `load'
13:19:13 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/bin/unicorn:23:in `<main>'
13:19:13 E, [2015-07-18T13:09:25.806791 #2239] ERROR -- CoreAPI: Invalid uuid or unsupported uuid:  in Dcmgr::Models::Network
```

**Comment by Metallion** [comment]
The CI is so unstable right now. :( How can we investigate the mysql problem?

**Comment by hansode** [comment]
> How can we investigate the mysql problem?

We can't do anymore.
Because the testing box was removed.

**Comment by Metallion** [comment]
I see. That's a shame. :( We should really do something about the unstable CI though. Probably starting with https://github.com/axsh/wakame-vdc/issues/584.

Anyway, this pull request looks ok. +1

**Pull request merged**
