### PR TITLE
Fix haproxy updater

### LINKED ISSUE #559: KVM: lb-cluster test failed case
### Problem

Some lb-cluster tests failed at the same point:

```
15:21:16 Running ./t.lb.tcp.node.multi.balancing.sh
...
15:25:57 test_balance_algorithm_leastconn
15:25:57 ---
15:25:57 :id: lb-ajtpa3fc
15:25:57 :uuid: lb-ajtpa3fc
15:25:57 :account_id: a-shpoolxx
15:25:57 :instance_id: i-99d5nd02
15:25:57 :instance_protocol: tcp
15:25:57 :instance_port: 80
15:25:57 :balance_algorithm: leastconn
15:25:57 :cookie_name: shunit2cookie
15:25:57 :description: ''
15:25:57 :private_key: ''
15:25:57 :public_key: ''
15:25:57 :created_at: 2015-04-28 06:22:55.000000000 Z
15:25:57 :updated_at: 2015-04-28 06:25:54.000000000 Z
15:25:57 :deleted_at: 
15:25:57 :display_name: 
15:25:57 :allow_list:
15:25:57 - 0.0.0.0
15:25:57 :httpchk_path: ''
15:25:57 :state: running
15:25:57 :status: online
15:25:57 :target_vifs:
15:25:57 - :network_vif_id: vif-5d320ri8
15:25:57   :instance_id: i-ij9d26f3
15:25:57   :display_name: ''
15:25:57   :fallback_mode: 'off'
15:25:57 - :network_vif_id: vif-e4z0gh21
15:25:57   :instance_id: i-b2uyj7xd
15:25:57   :display_name: ''
15:25:57   :fallback_mode: 'off'
15:25:57 - :network_vif_id: vif-g5qgwlzu
15:25:57   :instance_id: i-cwj8jrqz
15:25:57   :display_name: ''
15:25:57   :fallback_mode: 'off'
15:25:57 :vif:
15:25:57 - :vif_id: vif-8pck3h01
15:25:57   :vif_index: 0
15:25:57   :network_id: nw-demo1
15:25:57   :ipv4:
15:25:57     :address: 10.0.2.103
15:25:57     :nat_address: 
15:25:57 - :vif_id: vif-26z41hk6
15:25:57   :vif_index: 1
15:25:57   :network_id: nw-demo8
15:25:57   :ipv4:
15:25:57     :address: 10.1.0.10
15:25:57     :nat_address: 
15:25:57 :inbounds:
15:25:57 - :port: 8080
15:25:57   :protocol: tcp
15:26:00 expected_instance_uuid: i-cwj8jrqz
15:26:00 1. actual_instance_uuid: i-cwj8jrqz
15:26:00 2. actual_instance_uuid: i-ij9d26f3
15:26:00 ASSERT:should be the same uuid expected:<i-cwj8jrqz> but was:<i-ij9d26f3>
15:26:00 3. actual_instance_uuid: i-cwj8jrqz
15:26:00 4. actual_instance_uuid: i-cwj8jrqz
15:26:00 5. actual_instance_uuid: i-b2uyj7xd
15:26:00 ASSERT:should be the same uuid expected:<i-cwj8jrqz> but was:<i-b2uyj7xd>
15:26:00 ./../../../shunit2: line 775: 28611 Killed                  curl -fsSkL http://${load_balancer_ipaddr}:${port}/cgi-bin/sleep.cgi > /dev/null 2>&1
15:26:00 ./../../../shunit2: line 775: 28612 Killed                  curl -fsSkL http://${load_balancer_ipaddr}:${port}/cgi-bin/sleep.cgi > /dev/null 2>&1
15:26:00 ---
15:26:00 - i-cwj8jrqz
```

### Solution Candicates

+ https://github.com/axsh/wakame-vdc/compare/fix-haproxy-updater
   + fix/improbe upstart system job for haproxy_updater
      + prevent from restarting the job too fast
      + decrease io-load
   + build/release new lb image
+ <del>https://github.com/axsh/wakame-vdc/compare/fix-lb-cluster-testing</del>
   + <del>set a proper sleep time</del>
   + no need so far

### PR DESCRIPTION
**Pull request by hansode**
### Problem

Sometimes the `haproxy_updator` upstart system job failed before initializing networking with wakame-init.

### Possible Solution

1. change respawn limitation to unlimited
2. add a proper sleep time before executing new process
3. build new lb machine image

I've already gotten good result in #559.
So if this PR is merged, please close #559.

### CODE REVIEW

**Comment by Metallion** [comment]
First of all, thank you so much for fixing this! :smiley_cat: 

But I feel like `respawn unlimited` is a little too aggressive in this case. How about calling `initctl start haproxy_updater` at the end of the `wakame-init` script instead?

**Comment by hansode** [comment]
> How about calling initctl start haproxy_updater at the end of the wakame-init script instead?

How do you call it?

**Comment by hansode** [comment]
> But I feel like respawn unlimited is a little too aggressive in this case.

Btw. Why did you use unlimited respawn in stud?

**Comment by Metallion** [comment]
> How do you call it?

Just add `initctl start haproxy_updater` as the end of `wakame-init`. This solution will only work if `wakame-init` is called again on reboot. Can you confirm if that is the case?

> Btw. Why did you use unlimited respawn in stud?

The problem was that STUD forks worker processes and then sleeps forever. When calling `initctl restart stud`, the main process would restart before the old child processes had died. It's easier if I explain step by step.

**STUD first start**

1) STUD upstart job starts on boot
  1.1) STUD main process forks worker child processes (1 per CPU core)
  1.2.1) STUD children start listening on TCP port `xxxx.`
  1.2.2) STUD main process sleeps forever

**STUD restart**

2) User makes PUT call to load balancer WebAPI
  2.1) Wakame-vdc sends AMQP call with new settings to load blaancer
  2.2) The updater script in load balancer updates config files and calls `initctl restart stud`
  2.3) Upstart kills the main STUD process (but children are still alive)
  2.4) Upstart starts new STUD main process (the old children are still alive)
  2.5) New STUD process tries to listen on TCP port `xxxx`(the old children are still alive)
  2.6) The new STUD process fails because TCP port `xxxx` is still in use by the old children

**Comment by hansode** [comment]
Thanks for stud background.

**Comment by hansode** [comment]
I think that `respawn` parameter should not be changed in this case/issue.
The porpose of this change is adding `SLEEP`.

**Comment by Metallion** [comment]
After discussing in person, I believe the unlimited respawn is OK for the following reasons:

* My idea of adding a start to `wakame-init` doesn't work because the load balancer is using the standard instance's `wakame-init`. I wrongly assumed that it uses a specialized version.

* This is a specialized upstart job that will only be used specifically for this Wakame-vdc load balancer appliance. There is no need to keep a scenario where HAProxy isn't running in mind.

Merging.

**Pull request merged**
