### PR TITLE
Fix LXC driver

### PR DESCRIPTION
**Pull request by Metallion**
Fix the lxc driver according to the details reported by @habuka036 https://github.com/axsh/wakame-vdc/issues/762

### CODE REVIEW

**Comment by Metallion** [comment]
The dummy and kvm failures are a problem of Jenkins itself rather than the tests.

```
18:16:35 hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
18:16:35        at hudson.remoting.Request.abort(Request.java:297)
18:16:35        at hudson.remoting.Channel.terminate(Channel.java:844)
18:16:35        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
18:16:35        at ......remote call to phys026b.opty(Native Method)
18:16:35        at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
18:16:35        at hudson.remoting.Request.call(Request.java:172)
18:16:35        at hudson.remoting.Channel.call(Channel.java:777)
18:16:35        at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
18:16:35        at com.sun.proxy.$Proxy52.join(Unknown Source)
18:16:35        at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:992)
18:16:35        at hudson.Launcher$ProcStarter.join(Launcher.java:389)
18:16:35        at org.jenkinsci.plugins.managedscripts.ScriptBuildStep.perform(ScriptBuildStep.java:187)
18:16:35        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
```

It seems like some jobs also got stuck in a pending state. Since the CI environment gets rebuilt nightly, I am just going to kill the deadlocked jobs and run the CI again to see if the problems got resolved in the nightly build.

**Comment by Metallion** [comment]
Rerunning the CI now.

**Comment by Metallion** [comment]
The current LXC failure was due to a bug in the wakame-init script inside the load balancer test image. After rebuilding the image with the changes from https://github.com/axsh/wakame-vdc/pull/777, the CI was green.

It didn't put a new comment on this PR because I ran only the LXC job but  you can check that it's green here. http://ci.wakame.jp/job/lxc.smoke.trigger/3121/console

**Comment by t-iwano** [comment]
:+1:

**Comment by t-iwano** [comment]
:+1:

**Pull request merged**
